pipeline:
  name: harness_test
  identifier: harness_test
  projectIdentifier: Azure
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github_1
        build: <+input>
  stages:
    - stage:
        name: har
        identifier: har
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: github_1
                    build:
                      type: branch
                      spec:
                        branch: main
                  when:
                    stageStatus: Success
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: ls -ltr
    - stage:
        name: dele
        identifier: dele
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo aws sts get-caller-identity
                    environmentVariables: []
                    outputVariables: []
                    delegateSelectors:
                      - docker-delegate
                  timeout: 10m
        tags: {}
