pipeline:
  name: harness-infra
  identifier: harnessinfra
  projectIdentifier: development
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: apply
        identifier: apply
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: assume
                  identifier: assume
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |
                          echo "current role: $(aws sts get-caller-identity | jq -r .Arn)"

                          assume="$(aws sts assume-role --role-arn $ROLE_ARN --role-session-name '<+stage.name>-<+pipeline.executionId>')"

                          export AWS_ACCESS_KEY_ID=$(echo $assume | jq -r .Credentials.AccessKeyId)
                          export AWS_SECRET_ACCESS_KEY=$(echo $assume | jq -r .Credentials.SecretAccessKey)
                          export AWS_SESSION_TOKEN=$(echo $assume | jq -r .Credentials.SessionToken)

                          echo "assumed role: $(aws sts get-caller-identity | jq -r .Arn)"
                    environmentVariables:
                      - name: AWS_ACCESS_KEY_ID
                        type: String
                        value: <+secrets.getValue("aws_access_key_id")>
                      - name: AWS_SECRET_ACCESS_KEY
                        type: String
                        value: <+secrets.getValue("aws_secret_access_key")>
                      - name: AWS_DEFAULT_REGION
                        type: String
                        value: us-west-2
                      - name: ROLE_ARN
                        type: String
                        value: <+input>
                    outputVariables:
                      - name: AWS_ACCESS_KEY_ID
                        type: Secret
                        value: AWS_ACCESS_KEY_ID
                      - name: AWS_SECRET_ACCESS_KEY
                        type: Secret
                        value: AWS_SECRET_ACCESS_KEY
                      - name: AWS_SESSION_TOKEN
                        type: Secret
                        value: AWS_SESSION_TOKEN
                    delegateSelectors:
                      - riley-sa-cluser-development
                  timeout: 10m
                  failureStrategies: []
              - step:
                  type: TerraformPlan
                  name: plan
                  identifier: pla
                  spec:
                    configuration:
                      command: Apply
                      configFiles:
                        store:
                          type: Github
                          spec:
                            gitFetchType: Branch
                            connectorRef: account.Github
                            repoName: rssnyder/harness-infra
                            branch: main
                            folderPath: terraform/
                      secretManagerRef: harnessSecretManager
                      environmentVariables:
                        - name: AWS_REGION
                          value: us-west-2
                          type: String
                        - name: AWS_ACCESS_KEY_ID
                          value: <+execution.steps.assume.output.outputVariables.AWS_ACCESS_KEY_ID>
                          type: String
                        - name: AWS_SECRET_ACCESS_KEY
                          value: <+execution.steps.assume.output.outputVariables.AWS_SECRET_ACCESS_KEY>
                          type: String
                        - name: HARNESS_PLATFORM_API_KEY
                          value: <+secrets.getValue("harness_api_token")>
                          type: String
                        - name: HARNESS_ACCOUNT_ID
                          value: wlgELJ0TTre5aZhzpt8gVA
                          type: String
                        - name: AWS_SESSION_TOKEN
                          value: <+execution.steps.assume.output.outputVariables.AWS_SESSION_TOKEN>
                          type: String
                    provisionerIdentifier: something
                    delegateSelectors:
                      - riley-sa-cluser-development
                  timeout: 10m
                  failureStrategies: []
              - step:
                  type: HarnessApproval
                  name: approve
                  identifier: approve
                  spec:
                    approvalMessage: Please review the plan step output and approve based on the changes specified.
                    includePipelineExecutionHistory: true
                    approvers:
                      userGroups:
                        - account._account_all_users
                      minimumCount: 1
                      disallowPipelineExecutor: false
                    approverInputs: []
                  timeout: 1d
              - step:
                  type: TerraformApply
                  name: apply
                  identifier: apply
                  spec:
                    configuration:
                      type: InheritFromPlan
                    provisionerIdentifier: something
                    delegateSelectors:
                      - riley-sa-cluser-development
                  timeout: 10m
                  failureStrategies: []
        tags: {}
  storeType: INLINE
